data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
subset1 <- subset(data, data$Date == "2/2/2007" | data$Date == "1/2/2007")
Datetime <- paste(subset1$Date, subset1$Time)
Datetime2 <- as.POSIXct(Datetime,format="%d/%m/%Y %H:%M:%S")
newsubset2 <- cbind(subset1, Datetime2)
png(file="plot4.png", width = 480, height = 480)
par(mfcol=c(2,2))
par(mar=c(3,4,2,2))
with(newsubset2, plot(Global_active_power ~ Datetime2, type="l", ylab="Global Active Power", mar=c(3,4,2,2)))
with(newsubset2, plot(Sub_metering_1 ~ Datetime2, ylab="Energy sub metering", type = "n"))
points(newsubset2$Sub_metering_1 ~ newsubset2$Datetime2, type="l")
points(newsubset2$Sub_metering_2 ~ newsubset2$Datetime2, type="l", col="red")
points(newsubset2$Sub_metering_3 ~ newsubset2$Datetime2, type="l", col="blue")
legend("topright", lty=1, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"))
par(mar=c(4,4,2,2))
with(newsubset2, plot(Voltage ~ Datetime2, type="l", xlab="datetime"))
with(newsubset2, plot(Global_reactive_power ~ Datetime2, type="l", xlab="datetime"))
dev.off()
