data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
subset1 <- subset(data, data$Date == "2/2/2007" | data$Date == "1/2/2007")
Datetime <- paste(subset1$Date, subset1$Time)
Datetime2 <- as.POSIXct(Datetime,format="%d/%m/%Y %H:%M:%S")
newsubset2 <- cbind(subset1, Datetime2)
par(mar=c(3,4,2,2))
with(newsubset2, plot(Global_active_power ~ Datetime2, type="l", ylab="Global Active Power (kilowatts)"))
dev.copy(png, file="plot2.png", width = 480, height = 480)
dev.off()
